- .github/release.yml
- .github/workspace_snippet.sh
This makes it easier to reliably use in downstream projects.
> Add release workflow

- addlicense.sh
- e2e/bzlmod/BUILD.bazel
- e2e/bzlmod/MODULE.bazel
- e2e/bzlmod/WORKSPACE
- e2e/bzlmod/rule_under_test.bzl
- e2e/bzlmod/tests.bzl
This is so that the BCR release step has some basic tests to check functionality before being available in BCR.
* Also adds a script to add missing license headers
> Add simple end-to-end tests for bzlmod.

- tests/truth_tests.bzl
This makes //tests:target_subject_test pass under Bazel on GitHub. The google-internal
path was just an oversight when initially exporting.
Work towards #11
> tests: Remove google-internal path from target_subject_test

- lib/truth.bzl
- lib/util.bzl
- tests/truth_tests.bzl
* Move a uninitialized suppression to the proper place
* Mark an unused var as unused
* Remove some unused private variables
Work towards #11
> style: fix buildifier warnings

- .bazelci/presubmit.yml
* Run all tests with bzlmod enabled
* Run e2e/bzlmod tests as a pre-check for BCR releases
> tests: add bzlmod coverage to CI config

- lib/private/compare_util.bzl
`actual_pos` and `expected_pos` were always equal, but read as if they weren't intended to be.
> cleanup: Deduplicate variables in compare_contains_exactly_predicates

- lib/private/compare_util.bzl
- tests/truth_tests.bzl
Fixes the following error when comparing two collections against each other with `contains_exactly` and `in_order`:
```
Error: 'NoneType' value has no field or method 'matched_value'
```
> fix: Record match for matching in-order elements

- MODULE.bazel
- dev_extension.bzl
- e2e/bzlmod/BUILD.bazel
- e2e/bzlmod/tests.bzl
The Python toolchains are only needed for dev purposes (doc generation).
Unfortunately, Bazel doesn't provide an easy way to mark a register_toolchains() call as dev-only. To work around this, we use an extension to create a repository whose contents depend on if its the root module or not. If its the root module, it means we're the rules_testing module and its the dev-dependency case, so write a build file with the real toolchains. If its not the root module, then its not the dev-dependency case, so write an empty build file.
Fixes #33
> fix: Don't require downstream users to register Python toolchains.

- MODULE.bazel
- dev_extension.bzl
This is to get the fix that allows configuring pip to use the same version of Python as the rules use.
> cleanup: upgrade to rules_python 0.22.0

- .bazelci/presubmit.yml
- MODULE.bazel
- docgen/BUILD
- docgen/docgen.bzl
The latest version of stardoc supports bzlmod, which makes developing much nicer than using workspace.
> cleanup: Upgrade to stardoc 0.5.6 and enable bzlmod for building docs

- lib/truth.bzl
This allows using them directly with arbitrary values without having to go through the expect object. This is helpful for when the value is manually constructed and the metadata needs more direct customization.
Fixes #54
> feat: publically expose the rest of the subjects

- lib/private/matching.bzl
- tests/matching/BUILD.bazel
- tests/matching/matching_tests.bzl
- tests/truth_tests.bzl
These come from some of experience from porting the cc rules to use rules_testing
* Also moves the matcher tests into their own file because the truth_tests.bzl file is getting large.
* Also switches the matcher tests to be basic tests, since they don't really require a target graph to be setup.
Fixed #44
> feat: add file_basename_equals, file_extension_in matchers

- lib/private/dict_subject.bzl
- tests/truth_tests.bzl
This makes it easier to perform checks on keys/values within dicts when different asserts may be required depending on the key.
Fixes #51
> feat: add DictSubject.get

- lib/private/BUILD
- lib/private/collection_subject.bzl
- lib/private/expect.bzl
- lib/private/expect_meta.bzl
- lib/private/matching.bzl
- lib/private/util.bzl
- lib/truth.bzl
- tests/truth_tests.bzl
This adds a generic method to perform arbitrary transformations on the collection's value. When performing a transformation, a human friendly description of the transformation is required. When possible, a description is inferred from the args.
Fixes #45
> feat: add CollectionSubject.transform

- lib/private/analysis_test.bzl
- tests/analysis_test_tests.bzl
This allows setting common rule attributes such as tags, visibility, target_compatible_with, etc. Before this change, this was only possibly by  manually invoking the underlying `testing.analysis_test()` rule to pass the `attr_values` arg. After this change, it is possible to do the equivalent by directly passing the corresponding attribute by name instead of nesting it within `attr_values`.
This allows setting several useful attributes, such as tags, target_compatible_with, etc.
Fixes #43
> feat: Allow setting common rule attributes for analysis tests

- docgen/BUILD
- docs/crossrefs.md
- lib/BUILD
- lib/private/BUILD
- lib/private/expect.bzl
- lib/private/struct_subject.bzl
- lib/private/truth_common.bzl
- lib/truth.bzl
- tests/struct_subject/BUILD.bazel
- tests/struct_subject/struct_subject_tests.bzl
- tests/test_util.bzl
StructSubject is a subject to wrap structs and return their values as other subjects. This makes it easier to test ad-hoc struct values, such as ones returned by helper functions, because a dedicated subject implementation doesn't need to be written. All that needs to be provided are the attribute names and factory functions to handle them.
Fixes https://github.com/bazelbuild/rules_testing/issues/53
> feat: Add StructSubject

- CHANGELOG.md
- docgen/docgen.bzl
- lib/private/default_info_subject.bzl
- lib/private/truth_common.bzl
- lib/test_suite.bzl
- lib/truth.bzl
- tests/struct_subject/struct_subject_tests.bzl
- tests/test_util.bzl
- tests/truth_tests.bzl
- tests/unit_test_tests.bzl
`tuple`s are as list-like or more than `depset`s, but previously resulted in a `fail` when passed to collection subject functions.
Along the way remove an incorrect comment about `str` being iterable, which it is in Python but not in Starlark.
> Add support for `tuple` to collection subjects

- .bazelci/presubmit.yml
The upcoming Bazel version defaults to having bzlmod enabled, which means workspace
builds will need to explicitly disable it to continue to be workspace-based.
https://github.com/bazelbuild/bazel/issues/18958
> chore: Disable Bzlmod explicitly for workspace setup

- MODULE.bazel
This removes a hack to make the dev-only register_toolchains() call not break the production configuration. This hack is no longer necessary as of rules_python 0.23.0 and higher. Version 0.27.0 is chosen because the latest release has some code for building Sphinx documentation I'd like to experiment with re-using.
Coincidentally, this should also fix an an issue with the Bazel@HEAD downstream CI pipeline running tests for Mac/Windows that should be skipped, but fail due to very early MODULE-phase errors. With this change, it's able to get past that failure and run enough that the Bazel@HEAD downstream CI should be happy. Note those tests aren't gauranteed to continue to work on those platforms, they just happen to.
Fixes https://github.com/bazelbuild/rules_testing/issues/76
> chore: upgrade (dev only dependency) rules_python 0.22.0 -> 0.27.0

- MODULE.bazel
- WORKSPACE.bazel
In doing so, make tests pass with `--experimental_sibling_repository_layout`.
> Update Stardoc to 0.6.2.

- MODULE.bazel
- WORKSPACE.bazel
Updates various dev dependencies to better support upcoming Bazel versions.
* stardoc 0.6.2 -> 0.7.1
* rules_python 0.20.0 -> 0.37.2
* rules_cc 0.0.13 (workspace only)
* protobuf 27.0 (necessary for rules_cc, workspace only)
* rules_java 7.11.1 -> 7.12.2
Work towards #108, #109, #114
> chore(deps): stardoc, rules_python, rules_cc, protobuf, rule_java

- .bazelci/presubmit.yml
Builds started failing with Bazel 5, because rules_java dependencies were upgraded.
> chore: upgrade CI from Bazel 5 to 6
